language: python
python:
    - 3.4
before_script:
    - pip install -r test_requirements.txt
script:
    - cd src/repo_manager
    - py.test --strict --cov=. --cov-report=term-missing
after_success:
  - coveralls debug
