language: python
python:
    - 3.4
before_script:
    - pip install -r test_requirements.txt
script:
    - py.test repo_manager --strict --cov=repo_manager --cov-report=term-missing
after_success:
  - coveralls debug
